# Generated by Django 5.1.5 on 2025-01-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_rename_user_cattlehealthtrackeruser"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="cattleHealthTrackerUser",
            new_name="User",
        ),
    ]
