# Generated by Django 5.2 on 2025-04-04 00:30

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_userapp_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapp",
            name="mobile_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="EG", unique=True
            ),
        ),
    ]
