# Generated by Django 5.2 on 2025-04-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_alter_userapp_mobile_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapp",
            name="two_fa_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
