# Generated by Django 5.2 on 2025-04-08 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0010_alter_userapp_options_alter_userapp_managers_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapp",
            name="role",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.userroles",
            ),
        ),
    ]
