# Generated by Django 5.1.5 on 2025-01-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medicalevents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cattle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_number", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("birth_date", models.DateField()),
                ("weight", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="CattleMedicalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_vaccination_date", models.DateField(null=True)),
                (
                    "vaccination_status",
                    models.CharField(
                        choices=[("UP", "Up to Date"), ("NU", "Not Up to Date")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "cattle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cattle.cattle"
                    ),
                ),
                (
                    "due_vaccine",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="medicalevents.vaccinationtypesenglish",
                    ),
                ),
            ],
        ),
    ]
